name: Automated Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install lua
        uses: leafo/gh-actions-lua@v7
        with:
          luaVersion: 5.3

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v3

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Lint sources
        run: |
          luacheck core plugins tests/test_*.lua

      - name: Run tests
        run: |
          lua test_class.lua -v
          lua test_locales.lua -v
        working-directory: tests
